name: update subs
run-name: update subs

on:
  schedule:
    - cron: '0 0 * * *'
      timezone: America/New_York
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-subs-file:
    runs-on: ubuntu-latest

    env:
      YOUTUBEAPISTRING: ${{ secrets.YOUTUBEAPISTRING }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run script
        run: node index.js

      - name: Commit & push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update sub count" || echo "No changes to commit"
          git push
